package com.training.app

import android.content.Context
import android.net.Uri
import org.json.JSONArray
import org.json.JSONObject
import java.io.DataInputStream
import java.io.File
import java.io.FileInputStream
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream
import kotlin.math.exp

/** Actual post-training test for the local character model. It generates from the saved weights; no fake response is inserted. */
object TrainedModuleTester {
    fun generate(model: DistributedModel, prompt: String, maxNewChars: Int = 256): String {
        require(prompt.isNotBlank()) { "A test question or prompt is required" }
        require(maxNewChars in 1..1024)
        val index = model.vocabulary.withIndex().associate { it.value to it.index }
        var current = prompt.lastOrNull()?.let { index[it] } ?: 0
        val out = StringBuilder(prompt)
        repeat(maxNewChars) {
            val row = model.weights[current]
            var best = 0
            var bestValue = Float.NEGATIVE_INFINITY
            for (i in row.indices) {
                if (row[i] > bestValue) { bestValue = row[i]; best = i }
            }
            out.append(model.vocabulary[best])
            current = best
        }
        return out.toString()
    }
}

object TrainingPackageExporter {
    private const val MAX_PACKAGE_BYTES = 8L * 1024L * 1024L

    suspend fun export(context: Context, engine: LocalTrainingEngine, analytics: GrowthAnalytics, destination: Uri): Boolean {
        val modelBytes = engine.savedModelBytes() ?: return false
        require(modelBytes.size.toLong() <= MAX_PACKAGE_BYTES)
        val metadata = JSONObject()
            .put("format", "training-package-v1")
            .put("createdAt", System.currentTimeMillis())
            .put("modelSteps", engine.readSavedModel()?.completedSteps ?: 0)
            .put("modelBytes", modelBytes.size)
            .put("hasTrainingCorpus", engine.hasTrainingCorpus())
        val records = analytics.records()
        val recordJson = JSONArray().apply {
            records.forEach { r ->
                this@apply.put(JSONObject()
                    .put("id", r.id)
                    .put("timestamp", r.timestamp)
                    .put("score", r.score)
                    .put("source", r.source)
                    .put("verified", r.verified)
                    .put("categories", JSONObject(r.categories.mapValues { it.value })))
            }
        }
        val output = context.contentResolver.openOutputStream(destination) ?: return false
        output.use { raw ->
            ZipOutputStream(raw.buffered()).use { zip ->
                put(zip, "training-model.bin", modelBytes)
                put(zip, "metadata.json", metadata.toString(2).toByteArray(Charsets.UTF_8))
                put(zip, "evaluation-history.json", recordJson.toString(2).toByteArray(Charsets.UTF_8))
                val corpus = engine.trainingCorpus()
                if (!corpus.isNullOrBlank()) put(zip, "training-corpus.txt", corpus.toByteArray(Charsets.UTF_8))
                put(zip, "README.txt", "Training package generated by the Training app. The model is the verified saved module; evaluation history contains only user-verified records.\n".toByteArray(Charsets.UTF_8))
            }
        }
        return true
    }

    private fun put(zip: ZipOutputStream, name: String, bytes: ByteArray) {
        require(bytes.size <= MAX_PACKAGE_BYTES)
        zip.putNextEntry(ZipEntry(name))
        zip.write(bytes)
        zip.closeEntry()
    }
}
